#!/usr/bin/env python3

from subprocess import Popen, PIPE
from pathlib import Path
from python_tools import PidUniqueChecker
import os

# pidfile and other directories
dir = Path(os.getenv('HOME'))/'.config'/'desktop-environment'
pidchecker = PidUniqueChecker('focus_indicate', keep_old=False)
pidchecker.start_program()


def focus_change_trigger(func):
    with Popen(['xprop', '-spy', '-root', '_NET_ACTIVE_WINDOW'], stdout=PIPE) as window_changer:
        while True:
            pidchecker.ensure_unique()

            # active window id
            # halts until there is output of the subprocess (a change of focus)
            window_id = window_changer.stdout.readline().decode('utf-8').split(' ')[-1].strip()
            func(window_id)


def indicate_focus(window_id):
    Popen(['i3-msg', '[class="^.*"] border pixel 0; border pixel 2'])
    #y = Popen(['xprop', '-id', window_id],stdout=PIPE).stdout.readlines()
    #y = '\n'.join(map(lambda x: x.decode('utf-8').strip(), y))
    #with open('/dev/pts/0', 'w') as f:
        #print(y, file=f)


focus_change_trigger(indicate_focus)

