#!/usr/bin/env python3
import click
from subprocess import Popen, PIPE
from pathlib import Path
from python_tools import get_active_pid, get_tty, is_python_file, METADIR
import json


metafile = METADIR / 'run_file_meta.json'
metafile.parent.mkdir(parents=True, exist_ok=True)


@click.command()
@click.option('--file', '-f', is_flag=False, help='File to run. Ignored if used with -s or --set-tty')
@click.option('--set-tty', '-s', is_flag=True, help='Set the output TTY to the TTY connected to the active terminal. Does nothing if there is no TTY connected. If this flag is set, --file is ignored.')
@click.option('--pytest', '-t', is_flag=True, help='run a testing suite with pytest')
def main(file: str = None, set_tty: bool = False, pytest: bool = False):
    '''this script executes FILE and sends output to a specified TTY.'''
    assert file or set_tty or pytest, 'Missing action! see --help'

    if set_tty:
        save_tty()
        return
    if pytest:
        run_python_test()
    if file:
        file = Path(file)
        assert file.exists(), f'{file.absolute()} does not exist.'
        if is_python_file(file):
            run_python_file(file)
        else:
            raise NotImplementedError


def save_tty():
    # get_tty returns false if it could not find a tty connected.
    if tty := get_tty(get_active_pid()):
        json.dump({'tty': tty}, metafile.open('w'))
        print('success')
    else:
        raise RuntimeError('no tty could be found')


def load_tty():
    return Path('/dev') / json.load(metafile.open('r'))['tty']


def run_python_file(file: Path):
    load_tty()
    clear_terminal(tty := load_tty())
    # print output to tty
    with open(tty, 'w') as f:
        # color output
        normal_c = '\u001b[37m'
        highlight_c = '\u001b[33m'

        colorer = Popen(['pygmentize', '-l', 'pytb'], stdout=f, stdin=PIPE)
        process = Popen(['python', file], stderr=colorer.stdin, stdout=f)
        print('\n'*3, file=f)
        print(f'{highlight_c}started process with PID {process.pid}{normal_c}', file=f)
        process.communicate()
        colorer.communicate()
        print(f'{highlight_c}Process with PID {process.pid} finished.{normal_c}', file=f)
        print('\n'*5, file=f)

def run_python_test():
    load_tty()
    clear_terminal(tty := load_tty())
    with open(tty, 'w') as f:
        normal_c = '\u001b[37m'
        highlight_c = '\u001b[33m'

        print('\n'*3, file=f)
        #print(f'{highlight_c}started process with PID {process.pid}{normal_c}', file=f)
        process = Popen(['pytest', '--color=yes'], stderr=f, stdout=f).communicate()
        print('\n'*3, file=f)

def clear_terminal(tty: str):
    # clear console
    with tty.open('w') as f:
        f.write('\033[2J\033[2H')


if __name__ == '__main__':
    main()
